# Generated by Django 4.2.16 on 2024-10-26 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("NG_Support_Web", "0002_image_listing"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="description",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="title",
        ),
    ]
