# Generated by Django 4.2.16 on 2024-10-28 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NG_Support_Web", "0004_amenity"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="city",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AddField(
            model_name="listing",
            name="country",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AddField(
            model_name="listing",
            name="location",
            field=models.CharField(default="", max_length=255),
        ),
    ]
