# Generated by Django 4.2.16 on 2024-10-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NG_Support_Web", "0005_listing_city_listing_country_listing_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="contact_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="listing",
            name="title",
            field=models.CharField(default="Untitled Listing", max_length=200),
        ),
    ]
