# Generated by Django 4.2.16 on 2024-10-29 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("NG_Support_Web", "0006_listing_contact_number_listing_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listings",
                to="NG_Support_Web.category",
            ),
        ),
    ]
