# Generated by Django 4.2.16 on 2024-10-29 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NG_Support_Web", "0007_listing_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="city",
            field=models.CharField(
                blank=True, default="Unknown", max_length=100, null=True
            ),
        ),
    ]
