# Generated by Django 4.2.16 on 2024-10-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NG_Support_Web", "0008_alter_listing_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="country",
            field=models.CharField(blank=True, default="Unknown", max_length=100),
        ),
        migrations.AlterField(
            model_name="listing",
            name="location",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
