# Generated by Django 4.2.16 on 2024-10-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NG_Support_Web", "0009_alter_listing_country_alter_listing_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="city",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AlterField(
            model_name="listing",
            name="contact_number",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="listing",
            name="country",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AlterField(
            model_name="listing",
            name="location",
            field=models.CharField(default="", max_length=255),
        ),
    ]
