# Generated by Django 4.2.16 on 2024-10-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NG_Support_Web", "0011_listing_latitude_listing_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="facebook_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="instagram_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="tagline",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="listing",
            name="video_link",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="whatsapp_number",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
