# Generated by Django 4.2.16 on 2024-10-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NG_Support_Web", "0013_alter_listing_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                default="static/img/l-4.jpg",
                null=True,
                upload_to="thumbnails/",
            ),
        ),
    ]
