# Generated by Django 4.2.16 on 2024-10-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NG_Support_Web", "0014_alter_listing_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="amenities",
            field=models.ManyToManyField(
                blank=True, related_name="listings", to="NG_Support_Web.amenity"
            ),
        ),
    ]
