# Generated by Django 4.2.16 on 2024-11-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NG_Support_Web", "0015_listing_amenities"),
    ]

    operations = [
        migrations.CreateModel(
            name="HouseRent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="House Rental", max_length=200)),
                ("description", models.TextField(blank=True)),
                ("contact_number", models.CharField(max_length=20)),
                ("location", models.CharField(default="", max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("bedrooms", models.IntegerField(default=1)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        default="static/img/landing-bg.png",
                        null=True,
                        upload_to="thumbnails/",
                    ),
                ),
                ("country", models.CharField(default="Unknown", max_length=100)),
                ("city", models.CharField(default="Unknown", max_length=100)),
                (
                    "amenities",
                    models.ManyToManyField(
                        blank=True,
                        related_name="house_rents",
                        to="NG_Support_Web.amenity",
                    ),
                ),
                (
                    "images",
                    models.ManyToManyField(
                        blank=True,
                        related_name="house_rents",
                        to="NG_Support_Web.image",
                    ),
                ),
            ],
        ),
    ]
