# Generated by Django 4.2.16 on 2024-11-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NG_Support_Web", "0017_houserent_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="houserent",
            name="address",
            field=models.CharField(default="", max_length=255),
        ),
    ]
