# Generated by Django 4.2.16 on 2024-11-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NG_Support_Web", "0019_skill_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="address",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="job",
            name="contact_number",
            field=models.CharField(default="N/A", max_length=15),
        ),
    ]
