# Generated by Django 4.2.16 on 2024-11-05 06:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("NG_Support_Web", "0020_job_address_job_contact_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
