# Generated by Django 4.2.16 on 2024-11-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NG_Support_Web", "0022_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="icon",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="service",
            name="keywords",
            field=models.TextField(default="N/A"),
        ),
    ]
