# Generated by Django 4.2.16 on 2024-11-05 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("NG_Support_Web", "0023_service_icon_service_keywords"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="category",
        ),
    ]
