# Generated by Django 4.2.16 on 2024-11-06 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NG_Support_Web", "0024_remove_service_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="service_thumbnails/"
            ),
        ),
    ]
