# Generated by Django 4.2.16 on 2024-11-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NG_Support_Web", "0026_service_amenities_service_contact_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="title",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
