# Generated by Django 4.2.16 on 2024-11-06 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("NG_Support_Web", "0027_service_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service_Amenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_amenities",
                        to="NG_Support_Web.service",
                    ),
                ),
            ],
        ),
    ]
