# Generated by Django 4.2.16 on 2024-11-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NG_Support_Web", "0028_service_amenity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="amenities",
            field=models.ManyToManyField(
                blank=True,
                related_name="services_list",
                to="NG_Support_Web.service_amenity",
            ),
        ),
    ]
