# Generated by Django 4.2.16 on 2024-11-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NG_Support_Web", "0031_rename_amenities_service_service_amenities"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="city",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AddField(
            model_name="service",
            name="country",
            field=models.CharField(default="Unknown", max_length=100),
        ),
    ]
